### ISSUE TITLE
No instructions for installation without Cask

### ISSUE THREAD

**Issue by earlthesquirrel** [Pavo-IM/ocbuilder#2]
Can you point me towards installation instructions for your package (not using the Cask?
Since the Cask is broken, I was going to try to install by hand, but I don't see any info on the installation process.

Thanks

**Comment by Pavo-IM** [comment]
Its a simple download the release and put in your Applications folder, right click on it and Open twice if using Mojave or above macOS version.

**Comment by earlthesquirrel** [comment]
I meant for building it from the repo.
I have the zip, but like to build things when I can...

**Comment by Pavo-IM** [comment]
Installation is completely different than compiling it yourself. In order to build the app yourself, you will need to remove the code signing feature and the Sparkle framework from the project. Unless you have your own Apple Developer account that has macOS Development application code signing access, then you simply change the developer account on the project.
