### ISSUE TITLE
Downloaded Release, unpacked app, selected folder, clicked Build -- nothing happens

### ISSUE THREAD

**Issue by earlthesquirrel** [Pavo-IM/ocbuilder#3]
I've downloaded the latest release zip.  Unpacked the app, launched the app.
Selected Release.  Left "with Kexts" selected.
Selected directory.
Click Build.

It says 

Cloning Lilu repo...

Compiling the latest committed Debug version of Lilu...

Then it stops.
I checked folder, nothing there... 

Checked app help and menus.  Don't see anything obvious I'm missing...

Can you point me towards the step(s) I'm missing?

**Comment by Pavo-IM** [comment]
Do you have Xcode installed and have opened Xcode and accepted the EULA? Right click on the app, Show Contents and run the binary inside terminal from `/Applications/OCBuilder.app/Contents/MacOS/OCBuilder` but leave the terminal open and watch for errors. Post a pic of the error.

**Comment by earlthesquirrel** [comment]
Yes, I have XCode installed.
I had additional tools installed (otherwise Git doesn't work)

Just tried firing up XCode separately.  It now is asking to install more additional tools (I'm guessing the latest update for IOS 14 needed new versions...)  So installing those.


The error says:

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance



Will try again after this update installs.

**Comment by earlthesquirrel** [comment]
After update, same error.

Cloning into 'Lilu'...
remote: Enumerating objects: 112, done.
remote: Counting objects: 100% (112/112), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 4138 (delta 59), reused 50 (delta 20), pack-reused 4026
Receiving objects: 100% (4138/4138), 4.32 MiB | 19.91 MiB/s, done.
Resolving deltas: 100% (2511/2511), done.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by Pavo-IM** [comment]
If you would have read the README of this repo in its entirety you would have seen `This app requires the full Xcode app installed in order to compile the source` You can not use this app with just command line tools. You also need to open Xcode accept the EULA and then since you have additional tools installed you will need to go to Xcode > Preferences > Locations tab and make sure you have Command Line Tools selected in Xcode like this.
![Screen Shot 2020-09-18 at 6 14 13 PM](https://user-images.githubusercontent.com/33814640/93649829-dcc05380-f9da-11ea-8e6e-1c3d0ab8285b.png)

**Comment by earlthesquirrel** [comment]
I do have Xcode installed, I had it open after the update.  I DID read the Readme..  Since I've got open projects in XCode, it "should" be ok.  So, don't be so friggin dismissive.

I use command line tools for Git as well.  

But apparently even with command line tools installed AND open projects which I build, both weren't sufficient to set this value in the preferences.

Explicitly setting this value in preferences seems to have been the fix.

**Comment by Pavo-IM** [comment]
This is because when you install additional tools, it replaces the command line tools location automatically. Even after installing Xcode after the installation of the additional tools the xcode-select perimeters are set. Since this app requires the "full" Xcode application with its built-in Command Line Tools location of xcode-select perimeters to be set manually. This is a requirement because of the way xcodebuild is used by the app to compile the repos it is cloning.

**Comment by earlthesquirrel** [comment]
That's fine, but it's not obvious from the ReadMe.  I have "full" Xcode installed.  I build swift projects.  I also use command line tools.  Nothing has shown this error until now.  Thank you for pointing out the preference to set.   You may want to indicate that in the ReadMe for others.
