### ISSUE TITLE
Can't get NASM MTOC install

### ISSUE THREAD

**Issue by jhsvip** [Pavo-IM/ocbuilder#36]
I have A new osx run OC builder, it required me to enter admin password, ---password entered, nothing happened 
After that. the ocbuilder.app stops work.
![A14D9453-5344-449D-B783-D2670E28A9D8](https://user-images.githubusercontent.com/63874546/89512894-71456c80-d806-11ea-824b-af94812d9a70.png)

Why is the interface of ocbuild prompting password different from other applications
The password input interface of hackintool is like this：
![9F45809F-06EF-4F24-8141-3076B9E5D058](https://user-images.githubusercontent.com/63874546/89513800-9dadb880-d807-11ea-8ff3-5e15af5837ed.png)
It can run normally after input passwords：
![6ED984ED-B613-41A1-8933-404987DC84AA](https://user-images.githubusercontent.com/63874546/89513936-c930a300-d807-11ea-8a8f-245d22ddbf37.png)

My OS version 11.0 Beta4 
Ocbuilder 7.4.4
Xcode 11.6

I think Ocbuilder Need to change a way to request the admin passwords.
Thanks for read my issues.
I installed them myself finally.

**Comment by Pavo-IM** [comment]
The way OCBuilder request the administrator password is done from the script, in order to get the input from the user it uses a `osascript` which is macOS native executable and AppleScript to display the input for the user. By all means if you know how to make the app take the input the Swift way and use that input from the user and add it as a variable into the bash script itself, please do a PR.
